baseurl: https://example.com
languageCode: en-us
defaultContentLanguage: en
isMultilingual: no
title: rich posert - grad
theme: hugo-theme-sam
pygmentsStyle: native
pygmentsCodefences: yes
params:
  dateform: Mon Jan 02, 2006
  dateformfull: Mon Jan 2 2006 15:04:05 EST
  description: rich posert's personal site.
  favicon: sam.ico
  footerText: rich is a bad grad student.
  homepage: main
  images: tn.png
  mainMenu:
    - link: posts
      text: posts
    - link: about
      text: who is rich?
  title: rich posert - grad
  videoBackground:
    overlay: rgba(0, 0, 0, 0.4)
    sources:
      - poster: /cispus.png
        source: /cispus.mp4
        type: video/mp4
imaging:
  quality: 75
