baseurl: https://posert-lab-blog.netlify.app/
languageCode: en-us
defaultContentLanguage: en
isMultilingual: no
title: rich posert - grad
theme: hugo-theme-sam
font: 'Open Sans'
pygmentsStyle: 'vim'
pygmentsCodefences: yes
params:
  dateform: Mon Jan 02, 2006
  dateformfull: Mon Jan 2 2006 15:04:05 EST
  description: rich posert's personal site.
  favicon: posert.ico
  footerText: rich is a bad grad student.
  homepage: main
  mainMenu:
    - link: about
      text: who is rich?
    - link: posts
      text: posts
    - link: mailto:rich@posertinlab.com
      text: email
    - link: https://twitter.com/posertinlab
      text: twitter
    - link: https://github.com/plethorachutney
      text: github
    - link: https://orcid.org/0000-0001-9010-2104
      text: orcid
    - link: https://keybase.io/plethorachutney
      text: keybase
  title: rich posert - grad
  videoBackground:
    overlay: rgba(0, 0, 0, 0.4)
    sources:
      - poster: /img/cispus.png
        source: /video/cispus.mp4
        type: video/mp4
imaging:
  quality: 75
